### ISSUE TITLE
Can't compile xfig on Mac 10.9

### ISSUE THREAD

**Issue by lolc** [mistydemeo/homebrew-xfig#1]
$ brew install xfig
==> Downloading http://downloads.sourceforge.net/mcj/xfig.3.2.5c.full.tar.gz
Already downloaded: /Library/Caches/Homebrew/xfig-3.2.5c.tar.gz
==> Patching
patching file fig.h
patching file w_export.c
patching file w_keyboard.c
patching file w_print.c
patching file w_util.c
==> chmod u+x Libraries
==> chmod u+r Doc/html/images/xfig-title.png
==> xmkmf
==> make clean
==> make CDEBUGFLAGS=-O0 w_fontpanel.o
./fig.h:68:10: fatal error: 'X11/Xlib.h' file not found
# include &lt;X11/Xlib.h&gt;

```
 ^
```

1 error generated.
make: **\* [w_fontpanel.o] Error 1

**Comment by krzakala** [comment]
How do you guys do this? I get 
brew install xfig
Error: No available formula for xfig

**Comment by SLAment** [comment]
Same here krzakala :/

**Comment by kevinzzz007** [comment]
My homebrew also can't find this package... @krzakala @SLAment

**Comment by Falkor** [comment]
you need to ``brew tap` this repo first. 

~~~bash
$> brew tap mistydemeo/homebrew-xfig
$> brew cask install xquartz      # is not yet done
$> brew install xfig                     # you might have conflicts with ghostscript and MacTeX which you can overwrite...
~~~

**Comment by soumitrasamanta** [comment]
Please, can you help me to resolve the following error: 

Thanks

.............
xmkmf

mv -f Makefile Makefile.bak
imake -DUseInstalled -I/usr/local/Cellar/imake/1.0.7_2/lib/X11/config
imake: No such file or directory
imake: Cannot exec /usr/local/opt/gcc/bin/cpp-6.
  Stop.
imake: Exit code 1.
  Stop.

**Comment by ryanphuang** [comment]
@soumitrasamanta It's probably because you only have GCC 7 installed why the makefile is looking for GCC 6. I couldn't find in the Makefiles where the GCC 6 is hard-coded. But a workaround is to install GCC 6 through homebrew and link it. It worked on my Mac.

```bash
brew install gcc@6
cd /usr/local/opt
rm /usr/local/opt/gcc
ln -s ../Cellar/gcc@6/6.3.0 gcc
```
The last three steps create a soft link of GCC 6 to the gcc location. You can revert the symlink to GCC 7 after compiling xfig if you want.

**Comment by soumitrasamanta** [comment]
@ryanphuang Thank you very much, it works.

**Comment by mistydemeo** [comment]
Assuming this is stale; should work with the newest version!
