### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by Harry1993** [mistydemeo/homebrew-xfig#11]
Hello Misty,

I run `brew tap mistydemeo/homebrew-xfig` then `brew install xfig`. Homebrew says:

```
Error: SHA256 mismatch
Expected: 5fe81ce4132b139667fbfaacdf04a026f0313a34d39c7f640024db894cced42a
Actual: 251a85b3bac687974f360d3796048c20ded3bf0bd69e0d1cfd1db23d013f89ed
```

Maybe the source has been updated?

Thanks,
Yanmao

**Comment by Harry1993** [comment]
What URL did you try? I try [this one](https://downloads.sourceforge.net/mcj/xfig-3.2.7.tar.xz) and it succeeds.

**Comment by mistydemeo** [comment]
I used `http://downloads.sourceforge.net/mcj/xfig-3.2.7.tar.xz`, but the HTTPS version is still returning the "disaster recovery mode" message for me. I'm guessing it'll be intermittently up or down for awhile.

**Comment by mistydemeo** [comment]
Looks like the issue is resolved now!

**Comment by Harry1993** [comment]
It works! Appreciated.
