### ISSUE TITLE
App default directory issue

### ISSUE THREAD

**Issue by chfarges** [mistydemeo/homebrew-xfig#13]
Hello,
Thanks to your formula, XFig works on my Mac on Mojave but I have a warning message when opening stating:

> Either you have a very old app-defaults file installed (Fig), or there is none installed at all. You should install the correct version or you may lose some features. This may be done with "make install" in the xfig source directory.

This error comes from the fact that XFig is looking for its configuration file (named Fig) in `/opt/X11/share/X11/app-defaults/` but this file is located in  `/usr/local/share/X11/app-defaults/`. Doing `sudo cp /usr/local/share/X11/app-defaults/Fig /opt/X11/share/X11/app-defaults/Fig` solves the problem but is not the ideal way I think.

Looking at XFig install options, I think that adding in your formula the option `--with-appdefaultdir=/opt/X11/share/X11/app-defaults` would solve the issue. Am I right ? Could you do the modification to the formula if this is working ?

Thanks!

**Comment by mistydemeo** [comment]
Unfortunately, writing to that location requires root access, so it can't be done from within a formula. Do you know if it's possible to get xfig to change where it's going to load that file from? I suspect unfortunately that this is going to be controlled by X11 and hence out of our control.

Maybe it just needs instructions for the user to manually put it in the right place?

**Comment by chfarges** [comment]
Hello !
As said in previous post, I think that adding in your formula the option --with-appdefaultdir=/opt/X11/share/X11/app-defaults would solve the issue. Could you do the modification to the formula if this is working ?
