### ISSUE TITLE
Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.

### ISSUE THREAD

**Issue by niu541412** [mistydemeo/homebrew-xfig#15]
MacOS Big Sur
Titel is the warning during the upgrade.

If I try to reinstall it, an error message is

> Last 15 lines from /Users/jomic/Library/Logs/Homebrew/xfig/02.make:
In file included from d_line.c:18:
./fig.h:193:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~
1 error generated.
make[1]: *** [d_ellipse.o] Error 1
1 error generated.
1 error generated.
1 error generated.
make[1]: *** [d_regpoly.o] Error 1
make[1]: *** [d_picobj.o] Error 1
make[1]: *** [d_spline.o] Error 1
1 error generated.
make[1]: *** [d_line.o] Error 1
make: *** [install-recursive] Error 1

> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/mistydemeo/homebrew-xfig/issues

**Comment by odousse** [comment]
Actually this warning comes on any version of MacOS.
