### ISSUE TITLE
xfig reports error on launch: very old or missing app-defaults file

### ISSUE THREAD

**Issue by jamesquilty** [mistydemeo/homebrew-xfig#17]
I appreciate very much that you've provided a brew formula for `xfig`! I was able to build `xfig` locally on macOS 10.15 and run it from the command-line (see transcript below) where it then opens in XQuarz 2.7.11. 

I'm not sure that this is an issue with the Homebrew build formula, but when I run `xfig` an error dialog is displayed:

```text
Either you have a very old app-defaults file installed (Fig),
or there is none installed at all.
You should install the correct version or you may lose some features.
```

An [online search](https://duckduckgo.com/?q=xfig+Either+you+have+a+very+old+app-defaults+file+installed+(Fig)%2C+or+there+is+none+installed+at+all) shows some rather old bug reports against MacPorts and Debian which were both closed `WORKSFORME`. The older [installation documentation](https://web.archive.org/web/20110808200607/http://epb.lbl.gov/xfig/installation.html) on the Xfig home page (ca. 2011 via the Wayback Machine) mentions `XAPPLRESDIR` but the current documentation on Sourceforge <http://mcj.sourceforge.net/installation.html> does not.

Is this something that could/should be corrected in the Homebrew build script?

#### Terminal Transcript

```shell
$ brew tap mistydemeo/xfig
$ brew install xfig
$ xfig
Warning: locale not supported by Xlib, locale set to C
Warning: X locale modifiers not supported, using default
Warning: Cannot convert string "-*-times-medium-r-normal--16-*-*-*-*-*-*-*,-*-*-medium-r-normal--16-*-*-*-*-*-*-*,*--16-*" to type FontSet
Warning: Unable to load any usable fontset
Warning: Unable to load any usable fontset
```

**Comment by jamesquilty** [comment]
The workaround mentioned in [MacPorts #14386](https://trac.macports.org/ticket/14386)
```shell
$ find /usr/local/Cellar -iname "app-defaults"
/usr/local/Cellar/xfig/3.2.7b/share/X11/app-defaults
$ export XAPPLRESDIR=/usr/local/Cellar/xfig/3.2.7b/share/X11/app-defaults
```
resolved the error message. The question remains is this something that could/should be corrected in the Homebrew build script?

[Aside: the warnings on the console remain, but are probably a different issue. I'm going to try updating to XQuartz 2.8 to see if the problems persist and, if they do, follow whatever advice I can find online e.g. <https://www.ckode.dk/linux/warning-locale-not-supported-by-xlib-locale-set-to-c/> to try to resolve the issue.]

**Comment by jamesquilty** [comment]
MacPorts has a port of Xfig <https://ports.macports.org/port/xfig> which, I understand from my colleague who is generating the Xfig files [1], runs without errors or warnings. From inspection of the MacPorts files, particularly [patch-Imakefile.diff](https://github.com/macports/macports-ports/blob/master/graphics/xfig/files/patch-Imakefile.diff), it looks like what needs to be done to avoid the runtime errors and warnings is to set the build environment variables. Of note from [patch-Imakefile.diff](https://github.com/macports/macports-ports/blob/master/graphics/xfig/files/patch-Imakefile.diff):

```diff
 XCOMM Uncomment and change XAPPLOADDIR to the directory where you want the
 XCOMM app-defaults resource files to go.  You will have to use the environment
... 
-XCOMM XAPPLOADDIR = /home/user/xfig
+XAPPLOADDIR = __PREFIX/lib/X11/app-defaults

```
 
which, for this formula should be `XAPPLOADDIR = __PREFIX/share/X11/app-defaults` where `__PREFIX` should be `/usr/local/Cellar/xfig/3.2.7b`. The other environment variables and, probably, code changes will obviously also need to be applied. That looks, relative to the alternative [1], reasonably straighforward... but I'll admit I don't know how to do it myself, yet. I'm happy to pitch-in as much as I can, but pointers on how to write a patch-and-build formula in Homebrew would help bring me up-to-speed.

Related: #13 reports the same problem as I have, but the setting of the `XAPPLRESDIR` environment variable cited above works around the problem reported there.

[1] Xfig is the _only_ package my colleague uses from MacPorts, using Homebrew for everything else. I'm not keen on doing the same and installing MacPorts just for Xfig because I'll want to uninstall Xfig and MacPorts later. [Uninstalling MacPorts](https://guide.macports.org/#installing.macports.uninstalling) looks to be more complicated from a system perspective, involving the deletion of Users and Groups, than amending the brew build formula so I can run `xfig` on rare occasion.

**Comment by mistydemeo** [comment]
I'll look into adapting this patch if possible.

**Comment by mistydemeo** [comment]
I believe I've fixed this! Can you try upgrading to 3.2.8a and see if it works for you now?

**Comment by jamesquilty** [comment]
I tried this and using a shim to set `XAPPLRESDIR` resolves the error, thanks!

**Comment by mistydemeo** [comment]
Great! Glad to hear it.
