### ISSUE TITLE
Fig2dev not installed as part of transfig (OS 10.10)

### ISSUE THREAD

**Issue by stalegjelsten** [mistydemeo/homebrew-xfig#2]
For me, fig2dev is not installed alongside transfig when installing from this repository. here is a [brew-gist](https://gist.github.com/5846f353c0000727c084). Any ideas what might cause this? As for the brew doctor complaining about Xcode 6.0.1: the 6.1 update is not available to me in the App Store, but I've installed the 6.1 Command line tools and chosen them with `sudo xcode-select -switch /Library/Developer/CommandLineTools/`

**Comment by luiceur** [comment]
good one! It works
