### ISSUE TITLE
Problem with xfig on MacOS

### ISSUE THREAD

**Issue by enriquesquintana** [mistydemeo/homebrew-xfig#9]
Hi,

I am having this problem when trying to install xfig on my macos:
MacBook$ brew install xfig
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
==> New Formulae
gitlab-gem                                  mkl-dnn                                     patchelf
==> Updated Formulae
abyss                     composer                  freetds                   mint                      skaffold
afsctool                  consul                    futhark                   modd                      subversion
amqp-cpp                  convox                    gegl                      mypy                      swift
annie                     cython                    gist                      nghttp2                   testssl
arangodb                  discount                  git-sizer                 nginx                     tmux
armor                     dnscrypt-proxy            globus-toolkit            nomad                     tup
artifactory               dnsdist                   grpc                      ocrmypdf                  vim
asio                      docker2aci                influxdb                  packmol                   wildfly-as
aspectj                   dub                       kubernetes-cli            paket                     wireguard-tools
babeld                    duti                      libhttpseverywhere        percona-server-mongodb    xonsh
bibtex2html               emscripten                librealsense              phpunit                   znapzend
binaryen                  firebase-cli              log4cplus                 rancher-cli
chronograf                flow                      mapnik                    sfk
clojure                   fn                        metabase                  singular

==> Installing xfig from mistydemeo/xfig
==> Downloading http://downloads.sourceforge.net/mcj/xfig.3.2.5c.full.tar.gz
Already downloaded: /Users/enrique/Library/Caches/Homebrew/xfig-3.2.5c.tar.gz
Error: uninitialized constant Formulary::FormulaNamespace463a4d1c15d015f781e9f88cd35d3086::Xfig::DATA
Did you mean?  Data
               Date
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/mistydemeo/homebrew-xfig/xfig.rb:24:in `patches'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1904:in `prepare_patches'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1094:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1895:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1894:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:12:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:92:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1872:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1092:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:108:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'

Can you provide any hint on what the problem may be? Thanks,

Enrique

**Comment by odousse** [comment]
Having the same problem (High Sierra).
